Update mips_testbench

diff --git a/bin/mips_testbench b/bin/mips_testbench
--- a/bin/mips_testbench
+++ b/bin/mips_testbench
@@ -857,4 +857,12 @@ then
 else
     echo "sw_ov.bin, SW, FAIL, Silvertrousers (Cyrus Goodarzi), doesn't catch trying to load out of range mem" | paste -sd ' ' >> ./test/output/"$dt"
 fi
+
+OUTPUT=$($1 "test_binaries/bin_bcd_test.bin")
+if test $? = 81
+then
+    echo "bin_bcd_test.bin, SW, PASS, Drakvor (Garham Amos Kwon), binary to bcd conversion success" | paste -sd ' ' >> ./test/output/"$dt"
+else
+    echo "bin_bcd_test.bin, SW, FAIL, Drakvor (Garham Amos Kwon), binary to bcd conversion failed" | paste -sd ' ' >> ./test/output/"$dt"
+fi
 cat ./test/output/"$dt"
