Update mips_testbench

diff --git a/bin/mips_testbench b/bin/mips_testbench
--- a/bin/mips_testbench
+++ b/bin/mips_testbench
@@ -11,6 +11,22 @@ then
 else
     echo "r0_test.bin, N/A, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
 fi
+OUTPUT=$(./bin/mips_simulator "test_binaries/invalid.bin")
+if test $? = 244
+then
+    echo "invalid.bin, N/A, PASS, Drakvor (Garham Amos Kwon), Invalid Instruction Exception, " | paste -sd ' ' >> ./test/output/"$dt"
+else
+    echo "invalid.bin, N/A, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
+fi
+
+OUTPUT=$(./bin/mips_simulator "test_binaries/mult_bt.bin")
+if test $? = 6
+then
+    echo "mult_bt.bin, MULT, PASS, Drakvor (Garham Amos Kwon), multiplication successfully performed, " | paste -sd ' ' >> ./test/output/"$dt"
+else
+    echo "mult_bt.bin, MULT, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
+fi
+
 OUTPUT=$(./bin/mips_simulator "test_binaries/multu_bt.bin")
 if test $? = 6
 then
@@ -27,6 +43,14 @@ else
     echo "mult_lg.bin, MULT, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
 fi
 
+OUTPUT=$(./bin/mips_simulator "test_binaries/mult_ng.bin")
+if test $? = 16
+then
+    echo "mult_ng.bin, MULT, PASS, Drakvor (Garham Amos Kwon), multiplication successfully performed, " | paste -sd ' ' >> ./test/output/"$dt"
+else
+    echo "mult_ng.bin, MULT, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
+fi
+
 OUTPUT=$(./bin/mips_simulator "test_binaries/div_ng_1.bin")
 if test $? = 254
 then
@@ -36,7 +60,7 @@ else
 fi
 
 OUTPUT=$(./bin/mips_simulator "test_binaries/div_ng_2.bin")
-if test $? = 2
+if test $? = 254
 then
     echo "div_ng_2.bin, DIV, PASS, Drakvor (Garham Amos Kwon), division successfully performed, " | paste -sd ' ' >> ./test/output/"$dt"
 else
@@ -84,7 +108,7 @@ else
 fi
 
 OUTPUT=$(./bin/mips_simulator "test_binaries/srav_lg.bin")
-if test $? = 0
+if test $? = 255
 then
     echo "srav_lg.bin, ADDIU, PASS, Drakvor (Garham Amos Kwon), operation successfully performed, " | paste -sd ' ' >> ./test/output/"$dt"
 else
@@ -92,20 +116,13 @@ else
 fi
 
 OUTPUT=$(./bin/mips_simulator "test_binaries/add_nj.bin")
-if test $? = 0
+if test $? = 246
 then
     echo "add_nj.bin, ADDIU, PASS, Drakvor (Garham Amos Kwon), Integer Overflow Exception, " | paste -sd ' ' >> ./test/output/"$dt"
 else
     echo "add_nj.bin, ADDIU, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
 fi
 
-OUTPUT=$(./bin/mips_simulator "test_binaries/invalid.bin")
-if test $? = 244
-then
-    echo "invalid.bin, N/A, PASS, Drakvor (Garham Amos Kwon), Invalid Instruction Exception, " | paste -sd ' ' >> ./test/output/"$dt"
-else
-    echo "invalid.bin, N/A, FAIL, Drakvor (Garham Amos Kwon), operation failed, " | paste -sd ' ' >> ./test/output/"$dt"
-fi
 
 OUTPUT=$(./bin/mips_simulator "test_binaries/add_bt.bin")
 if test $? = 3
@@ -140,7 +157,7 @@ else
 fi
 
 OUTPUT=$(./bin/mips_simulator "test_binaries/addiu_bt.bin")
-if test $? = A
+if test $? = 10
 then
     echo "addiu_bt.bin, ADDIU, PASS, Drakvor (Garham Amos Kwon), addition successfully performed, " | paste -sd ' ' >> ./test/output/"$dt"
 else
@@ -284,7 +301,7 @@ else
 fi
 
 OUTPUT=$(./bin/mips_simulator "test_binaries/slti_bt.bin")
-if test $? = 0
+if test $? = 1
 then
     echo "slti_bt.bin, SLTI, PASS, Drakvor (Garham Amos Kwon), operation successfully performed, " | paste -sd ' ' >> ./test/output/"$dt"
 else
